// UFOpaedia copy — original text in the register of a terse X-COM technical report.
import { ITEMS } from '../data/items';
import { CRAFT, CRAFT_WEAPONS } from '../data/craft';
import { UFOS } from '../data/ufos';
import { FACILITIES } from '../data/facilities';
import { ALIENS } from '../data/aliens';
import { DAMAGE_TYPE_NAMES } from '../data/items';
export type Category = 'Craft' | 'Craft Weapons' | 'Weapons and Equipment' | 'Heavy Weapons Platforms' | 'Alien Life Forms' | 'Alien Research' | 'UFO Components' | 'UFOs' | 'Base Facilities';
export interface Article { id: string; title: string; category: Category; sprite: string; stats: [string, string][]; body: string; requires?: string; }
const W: Record<string, string> = {
  pistol: 'Standard-issue sidearm. Low stopping power, but it fits any hand and leaves the other free for a grenade or a flare. Issued to every recruit until something better arrives from the workshop.',
  rifle: 'The squad workhorse. Reliable, accurate on the aimed setting, and its three-round burst will find a target at close range. Ammunition is cheap; carry spares.',
  'heavy-cannon': 'A shoulder-fired cannon that trades mobility for authority. Armour-piercing rounds punch through alien hull plating; the high-explosive shell clears rooms and walls alike.',
  'auto-cannon': 'Belt-fed heavy weapon with a fourteen-round magazine and a fast auto setting. Incendiary shells set cover ablaze; use them to deny ground rather than to hit.',
  'rocket-launcher': 'Single-shot launcher for small, large and incendiary rockets. Devastating against structures and clustered enemies. Keep the back-blast area clear of your own squad.',
  grenade: 'Fragmentation grenade with a settable fuse. Prime it before you throw it; a live grenade dropped at your feet detonates on your own turn timer.',
  'smoke-grenade': 'Generates a dense cloud that blocks line of sight in both directions. Screens an advance or a retreat. Troops who stand in it for long will start to choke.',
  'proximity-grenade': 'Arms after it lands and detonates when anything moves next to it. Cover a corridor or a UFO door and let the aliens come to it.',
  'high-explosive': 'Demolition pack. Enough charge to breach a UFO hull or level a farmhouse. Set the timer, place it, walk away.',
  'electro-flare': 'Chemical light source. Throw it ahead of the squad on night missions to extend visible range around the point of impact.',
  'stun-rod': 'Electrified prod for taking aliens alive. Requires an adjacent target and a steady hand. A live specimen is worth far more to the laboratory than a corpse.',
  'motion-scanner': 'Handheld detector that displays movement within nine tiles, through walls. It shows motion, not identity: a civilian and a Chryssalid look the same on the screen.',
  'medi-kit': 'Field surgical kit. Heal closes fatal wounds and restores a little health; stimulant revives the stunned; painkiller steadies morale. Ten charges of each.',
  'psi-amp': 'Amplifier that lets a trained operative project panic or seize control of an alien mind. Effectiveness depends on the user\'s psionic skill and the target\'s strength of will.',
  'mind-probe': 'Alien device that reads a target\'s statistics at a distance. Useful for choosing which alien to shoot first, and which to keep alive.',
  'laser-pistol': 'First fruit of the laser programme. No ammunition, no reloading, and a burst setting the conventional pistol never had.',
  'laser-rifle': 'The finest weapon Earth can build unaided. Accurate, tireless and light. Most squads never go back to the rifle once these reach the armoury.',
  'heavy-laser': 'A laser built around a larger emitter. Its single beam will stop a Muton, but it is slow to aim and heavy to carry.',
  'plasma-pistol': 'Alien sidearm firing a bolt of contained plasma. Outperforms every conventional weapon we field. The clip is Elerium-based and cannot yet be refilled.',
  'plasma-rifle': 'Standard alien infantry weapon. Accurate, powerful and fast to fire. Recovered examples are issued directly to the squad once the clip is understood.',
  'heavy-plasma': 'The heaviest alien hand weapon. A single shot will kill most targets outright and its clip lasts a full mission. The aliens issue it to their veterans.',
  'small-launcher': 'Alien grenade launcher that lobs a stun bomb in an arc. The preferred instrument for capturing live specimens without walking up to them.',
  'blaster-launcher': 'Guided alien launcher. Its bomb follows up to eight waypoints set by the operator before detonating with immense force. Treat it with respect.',
  'alien-grenade': 'Compact alien explosive with nearly twice the yield of our own grenade. Recovered from most alien soldiers.',
  'personal-armour': 'Body armour built from alien alloy plates over a ballistic weave. Turns pistol fire and reduces plasma burns to survivable injuries.',
  'power-suit': 'Full-body powered armour with an alloy exoskeleton and an internal Elerium cell. Withstands direct plasma hits. A squad in these suits is a different squad.',
  'flying-suit': 'Power Suit fitted with alien anti-gravity units. The wearer can hover over walls, rooftops and open ground. Nowhere on the map is out of reach.',
  'alien-alloys': 'The material of every UFO hull. Light, immensely strong and impossible to reproduce. Recovered by cutting up crashed craft; consumed by everything we build from it.',
  'elerium-115': 'Element 115. Source of the power that drives alien craft, weapons and armour. It cannot be manufactured, only recovered, and every unit spent is gone.',
  'ufo-power-source': 'Elerium reactor recovered from a UFO. Provides the energy density needed for our own alien-technology craft. Destroyed if the reactor is hit in combat.',
  'ufo-navigation': 'Alien navigation console. Its interface to the power source is the key to controlling anti-gravity flight.',
  'alien-food': 'Nutrient tanks found aboard larger craft. Their contents include tissue of terrestrial origin.',
  'alien-entertainment': 'A device that stimulates the alien nervous system directly. Its purpose aboard a warship is unclear.',
  'alien-reproduction': 'Cloning apparatus. Confirms that the alien soldiers we face are grown, not born.',
  'alien-surgery': 'Automated surgical table with restraints sized for humans and for cattle.',
  'examination-room': 'Scanning equipment for the detailed study of captured subjects.',
  'alien-habitat': 'Living quarters recovered from a large UFO. The aliens plan for long deployments.',
};
const HWP: Record<string, string> = { 'tank-cannon': 'Tracked weapons platform with a 60 mm cannon. Slow to turn, hard to kill, and it draws fire the squad cannot afford to take.', 'tank-rocket': 'Tracked platform mounting a rocket launcher. Eight rockets, each enough to open a UFO or flatten a barn.', 'tank-laser': 'Tank chassis with a laser cannon in place of the gun. Unlimited fire without a supply column.', 'hovertank-plasma': 'Anti-gravity platform with alien alloy armour and a plasma cannon. It flies. The aliens have nothing quite like it.', 'hovertank-launcher': 'Hovertank fitted with a fusion launcher. Guided bombs of enormous yield; three per sortie.' };
const CR: Record<string, string> = { skyranger: 'Long-range transport for fourteen troops and three heavy weapons platforms. Unarmed and slow. Its rear ramp is the first thing every recruit remembers.', interceptor: 'Conventional supersonic fighter with two hardpoints. Fast enough to catch a scout, fragile against anything larger.', firestorm: 'Our first craft built around a recovered power source. Faster than any UFO short of a Battleship, fuelled by Elerium.', lightning: 'Alien-technology transport with a single hardpoint and room for twelve troops. Its hull absorbs punishment a Skyranger never could.', avenger: 'The ultimate craft. Twenty-six troops, four platforms, two hardpoints, and range enough to reach Mars.' };
const CW: Record<string, string> = { stingray: 'Short-range air-to-air missile. Six shots, moderate damage, adequate against scouts.', avalanche: 'Long-range heavy missile. Three shots of real authority; the standard fit for hunting larger craft.', cannon: 'Rapid-fire cannon with a deep magazine. Cheap and close-ranged.', 'laser-cannon': 'Laser weapon for craft. Never needs rearming and sells for a handsome profit.', 'plasma-beam': 'Craft-mounted plasma weapon reverse-engineered from the heavy plasma. Outranges everything else we have.', 'fusion-ball': 'Guided fusion missile of tremendous yield. Two shots. Enough.' };
const AL: Record<string, string> = { sectoid: 'Small grey humanoids with oversized craniums. Physically weak, but their leaders are potent psionics and will attack the squad\'s minds from anywhere on the map.', floater: 'Cyborg torsos on anti-gravity units. They fly, they see well, and they are poor shots. Their terror unit is the Reaper.', snakeman: 'Serpentine reptiloids. Slow but heavily armoured, and they never travel without Chryssalids.', muton: 'Genetically engineered shock troops. Immensely strong and well armoured; only heavy weapons stop them quickly.', ethereal: 'Frail robed figures whose bodies barely function. Every one of them is a psionic of the first rank. They field Sectopods.', chryssalid: 'Fast, armoured and lethal at close quarters. A victim of its claws rises as a zombie and hatches a new Chryssalid. Kill it at range.', silacoid: 'A crawling mass of molten organic matter. Slow, immune to fire, and it leaves a burning trail.', celatid: 'Floating organism that spits acid with unnerving accuracy. Fragile once found.', reaper: 'Bipedal beast the size of a car. Charges and bites. Burns readily.', cyberdisc: 'Flying disc with a plasma weapon and thick armour. Its power core detonates when it is destroyed.', sectopod: 'Heavy walking weapon platform. Nearly immune to conventional fire; lasers are the answer.', zombie: 'A Chryssalid victim, shambling and mindless. Killing it releases the creature growing inside.' };
const RES: Record<string, [string, string]> = { 'alien-origins': ['Alien Origins', 'Interrogation confirms a single directing intelligence behind the invasion, operating from a base somewhere beyond Earth. The races we fight are servants, grown to order. Further captives may reveal where the orders come from.'], 'the-martian-solution': ['The Martian Solution', 'The alien leaders speak of Cydonia on Mars: a base of immense age from which the war is directed. It can be reached only by a craft with the range and hull to survive the journey. Build the Avenger.'], 'cydonia-or-bust': ['Cydonia or Bust', 'The Cydonia complex is mapped. Below its surface lies the brain that commands every alien on Earth. A single assault force, landed by Avenger, must fight through the surface defences and destroy it. There will be no second attempt.'], 'laser-weapons': ['Laser Weapons', 'Our own lasers, built without alien help. The programme yields a pistol first, then a rifle and a heavy weapon.'], 'ufo-construction': ['UFO Construction', 'We now understand how alloy hull, power source and navigation unit fit together. Our own craft can follow.'], 'psionic-laboratory': ['Psionic Laboratory', 'Training facility that measures and develops psionic strength and skill in our soldiers. Ten operatives at a time, one month per cycle.'], 'new-fighter-craft': ['New Fighter Craft', 'Design for the Firestorm, an interceptor built around a UFO power source.'], 'new-fighter-transporter': ['New Fighter-Transporter', 'Design for the Lightning, an armed troop carrier of alien construction.'], 'ultimate-craft': ['Ultimate Craft', 'Design for the Avenger, capable of reaching Cydonia.'] };
const UF: Record<string, string> = { 'small-scout': 'The smallest alien craft: a single pilot on a survey run. Unarmed and easily downed. Its power source is the cheapest route to Elerium we have.', 'medium-scout': 'A scout with a crew of three or four and a light weapon. Common in the early months.', 'large-scout': 'The largest survey craft. Carries an engineer and a navigator worth capturing.', abductor: 'Craft equipped for the collection of specimens, terrestrial and human. Two decks.', harvester: 'Collection craft for livestock. Escorted by terror units in the field.', 'supply-ship': 'Freighter that resupplies alien bases. Heavily built; its cargo is the richest recovery in the game.', 'terror-ship': 'Troop carrier for terror missions against cities. Heavily armed and crewed.', battleship: 'The largest alien craft. It attacks bases, leads infiltrations and carries a commander. Only alien-technology weapons will bring one down.' };
const FA: Record<string, string> = { 'access-lift': 'Entrance to the base. Every other facility must connect to it. If the aliens come, they come through here and the hangars.', 'living-quarters': 'Accommodation for fifty personnel of any kind.', 'general-stores': 'Storage for fifty units of equipment, alloys, Elerium and recovered artefacts.', laboratory: 'Workspace for fifty scientists.', workshop: 'Workspace for fifty engineers.', 'small-radar': 'Detects craft within 1,500 km on one check in ten every half hour.', 'large-radar': 'Detects craft within 2,250 km on one check in five.', 'missile-defences': 'Surface-to-air missiles against attacking UFOs.', 'laser-defences': 'Laser battery for base defence.', 'plasma-defences': 'Plasma battery for base defence.', 'fusion-ball-defences': 'The heaviest base defence we can build.', 'grav-shield': 'Doubles the effect of every defence facility by holding the attacker in place for a second volley.', 'mind-shield': 'Screens the base from alien detection.', 'psionic-laboratory': 'Trains ten soldiers a month in psionic skill.', 'hyper-wave-decoder': 'Detects every alien craft within 2,400 km and decodes its race and mission.', 'alien-containment': 'Holds ten live aliens for interrogation.', hangar: 'Houses one craft. Occupies four cells.' };
function statsFor(id: string): [string, string][] {
  const d = ITEMS[id]; if (!d) return []; const st: [string, string][] = [];
  const mode = (n: string, m?: { tu: number; accuracy: number }) => { if (m) st.push([n, `${m.tu}% TU · ${m.accuracy}% accuracy`]); };
  mode('Snap shot', d.snap); mode('Aimed shot', d.aimed); mode('Auto shot', d.auto); mode('Melee', d.melee);
  if (d.damage !== undefined) st.push(['Damage', `${d.damage} ${DAMAGE_TYPE_NAMES[d.damageType ?? 'ap']}`]); if (d.clipSize) st.push(['Rounds', String(d.clipSize)]); if (d.blastRadius) st.push(['Blast radius', `${d.blastRadius} tiles`]);
  if (d.armour) { const a = d.armour.values; st.push(['Armour front/side/rear/under', `${a.front} / ${a.left} / ${a.rear} / ${a.under}`]); }
  st.push(['Weight', String(d.weight)], ['Size', `${d.size.w}×${d.size.h}`]); if (d.costBuy) st.push(['Purchase', `$${d.costBuy.toLocaleString('en-GB')}`]); if (d.costSell) st.push(['Sale value', `$${d.costSell.toLocaleString('en-GB')}`]);
  return st;
}
export const ARTICLES: Article[] = [];
for (const id of Object.keys(CR)) { const c = CRAFT[id]; ARTICLES.push({ id: `craft-${id}`, title: c.name, category: 'Craft', sprite: c.sprite, stats: [['Max speed', `${c.speedMax} kt`], ['Damage capacity', String(c.damageMax)], ['Weapons', String(c.weapons)], ['Troops', String(c.soldiers)], ['HWPs', String(c.hwps)], ['Fuel', c.fuelItem ? `${c.fuelMax} Elerium` : String(c.fuelMax)]], body: CR[id], requires: c.requiresResearch }); }
for (const id of Object.keys(CW)) { const c = CRAFT_WEAPONS[id]; ARTICLES.push({ id: `cw-${id}`, title: c.name, category: 'Craft Weapons', sprite: c.sprite, stats: [['Damage', String(c.damage)], ['Range', `${c.range} km`], ['Accuracy', `${c.accuracy}%`], ['Ammunition', String(c.ammoMax)], ['Reload (standard)', `${c.reloadStandard} s`]], body: CW[id], requires: ITEMS[c.storeItem]?.requiresResearch }); }
for (const id of Object.keys(W)) { const d = ITEMS[id]; if (!d) continue; ARTICLES.push({ id, title: d.name, category: d.category === 'artefact' || d.category === 'alloys' || d.category === 'elerium' ? 'UFO Components' : 'Weapons and Equipment', sprite: d.sprite, stats: statsFor(id), body: W[id], requires: d.requiresResearch ?? (d.category === 'artefact' || d.category === 'alloys' || d.category === 'elerium' ? id : undefined) }); }
for (const id of ['pistol-clip', 'rifle-clip', 'hc-ap-ammo', 'hc-he-ammo', 'hc-in-ammo', 'ac-ap-ammo', 'ac-he-ammo', 'ac-in-ammo', 'small-rocket', 'large-rocket', 'incendiary-rocket', 'plasma-pistol-clip', 'plasma-rifle-clip', 'heavy-plasma-clip', 'stun-bomb', 'blaster-bomb']) { const d = ITEMS[id]; ARTICLES.push({ id, title: d.name, category: 'Weapons and Equipment', sprite: d.sprite, stats: statsFor(id), body: `Ammunition. ${d.clipSize} rounds of ${d.damage} ${DAMAGE_TYPE_NAMES[d.damageType ?? 'ap'].toLowerCase()} damage per clip.${d.alienArtefact ? ' Elerium-based; recovered from the field or manufactured once understood.' : ''}`, requires: d.requiresResearch }); }
for (const id of Object.keys(HWP)) { const d = ITEMS[id]; const h = d.hwp!; ARTICLES.push({ id, title: d.name, category: 'Heavy Weapons Platforms', sprite: d.sprite, stats: [['Time units', String(h.stats.tu)], ['Health', String(h.stats.health)], ['Armour front/side/rear/under', `${h.armour.front} / ${h.armour.left} / ${h.armour.rear} / ${h.armour.under}`], ['Ammunition', h.ammoRounds ? String(h.ammoRounds) : 'Unlimited'], ['Sale value', `$${d.costSell.toLocaleString('en-GB')}`]], body: HWP[id], requires: d.requiresResearch }); }
for (const id of Object.keys(AL)) { const a = ALIENS[id]; const r = a.ranks.soldier ?? a.ranks.terrorist!; ARTICLES.push({ id: `alien-${id}`, title: a.name, category: 'Alien Life Forms', sprite: `unit/${id}/4/idle`, stats: [['Time units', String(r.stats.tu)], ['Health', String(r.stats.health)], ['Reactions', String(r.stats.reactions)], ['Firing accuracy', String(r.stats.firing)], ['Armour front/side/rear/under', `${r.armour.front} / ${r.armour.left} / ${r.armour.rear} / ${r.armour.under}`], ['Psionic', a.psionic ? 'Yes' : 'No']], body: AL[id], requires: id }); ARTICLES.push({ id: `autopsy-${id}`, title: `${a.name} Autopsy`, category: 'Alien Life Forms', sprite: `item/${id}-corpse`, stats: [], body: `Post-mortem examination of a ${a.name}. ${a.meleeOnly ? 'The creature carries no weapon; its body is the weapon.' : a.psionic ? 'The enlarged cerebrum supports the psionic capability observed in the field.' : 'Internal structure consistent with an engineered organism.'} Weak points noted in the armour report above. The corpse has no further research value.`, requires: id }); }
for (const [id, [title, body]] of Object.entries(RES)) ARTICLES.push({ id: `research-${id}`, title, category: 'Alien Research', sprite: 'ref/alien-core', stats: [], body, requires: id });
for (const id of Object.keys(UF)) { const u = UFOS[id]; ARTICLES.push({ id: `ufo-${id}`, title: u.name, category: 'UFOs', sprite: u.sprite, stats: [['Size', u.size], ['Damage capacity', String(u.damageMax)], ['Max speed', `${u.speedMax} kt`], ['Weapon power', u.weaponPower ? `${u.weaponPower} at ${u.weaponRange} km` : 'Unarmed'], ['Score', String(u.score)]], body: UF[id] }); }
for (const id of Object.keys(FA)) { const f = FACILITIES[id]; ARTICLES.push({ id: `facility-${id}`, title: f.name, category: 'Base Facilities', sprite: f.sprite, stats: [['Build time', `${f.buildDays} days`], ['Cost', `$${f.cost.toLocaleString('en-GB')}`], ['Maintenance', `$${f.maintenance.toLocaleString('en-GB')}/month`]], body: FA[id], requires: f.requiresResearch }); }
export const CATEGORIES: Category[] = ['Craft', 'Craft Weapons', 'Weapons and Equipment', 'Heavy Weapons Platforms', 'Alien Life Forms', 'Alien Research', 'UFO Components', 'UFOs', 'Base Facilities'];
export const articleById = (id: string) => ARTICLES.find((a) => a.id === id);
