// Twenty sampled rules from the 1994 original, checked against the shipped data tables.
import { describe, it, expect } from 'vitest';
import { ITEMS } from '../../src/data/items';
import { RESEARCH } from '../../src/data/research';
import { FACILITIES } from '../../src/data/facilities';
import { CRAFT, CRAFT_WEAPONS } from '../../src/data/craft';
import { UFOS } from '../../src/data/ufos';
import { ALIENS } from '../../src/data/aliens';
import { FUNDING, STARTING_STAFF } from '../../src/data/score';
import { COMPRESSION_SECONDS } from '../../src/core/state';

describe('sampled original rules', () => {
  it('1. Rifle fire modes: snap 25%/60, aimed 80%/110, auto 35%/35', () => { const r = ITEMS['rifle']; expect(r.snap).toMatchObject({ tu: 25, accuracy: 60 }); expect(r.aimed).toMatchObject({ tu: 80, accuracy: 110 }); expect(r.auto).toMatchObject({ tu: 35, accuracy: 35, shots: 3 }); });
  it('2. Pistol: snap 18%/60, aimed 30%/78; clip 12 rounds, 26 AP', () => { const p = ITEMS['pistol']; expect(p.snap).toMatchObject({ tu: 18, accuracy: 60 }); expect(p.aimed).toMatchObject({ tu: 30, accuracy: 78 }); expect(ITEMS['pistol-clip'].clipSize).toBe(12); expect(ITEMS['pistol-clip'].damage).toBe(26); });
  it('3. Heavy Plasma: auto 35%/50, snap 30%/75, aimed 60%/110; clip 115 plasma × 35', () => { const h = ITEMS['heavy-plasma']; expect(h.auto).toMatchObject({ tu: 35, accuracy: 50 }); expect(h.snap).toMatchObject({ tu: 30, accuracy: 75 }); expect(h.aimed).toMatchObject({ tu: 60, accuracy: 110 }); expect(ITEMS['heavy-plasma-clip']).toMatchObject({ damage: 115, damageType: 'plasma', clipSize: 35 }); });
  it('4. Plasma Rifle 80 plasma / 28 rounds; Plasma Pistol 52 / 26', () => { expect(ITEMS['plasma-rifle-clip']).toMatchObject({ damage: 80, clipSize: 28 }); expect(ITEMS['plasma-pistol-clip']).toMatchObject({ damage: 52, clipSize: 26 }); });
  it('5. Laser line: pistol 46, rifle 60, heavy 85, self-powered', () => { expect(ITEMS['laser-pistol'].damage).toBe(46); expect(ITEMS['laser-rifle'].damage).toBe(60); expect(ITEMS['heavy-laser'].damage).toBe(85); expect(ITEMS['laser-rifle'].damageType).toBe('laser'); expect(ITEMS['laser-rifle'].ammo ?? []).toHaveLength(0); });
  it('6. Explosives: Grenade 50, Alien Grenade 90, High Explosive 110, Proximity 70, all HE', () => { expect(ITEMS['grenade']).toMatchObject({ damage: 50, damageType: 'he' }); expect(ITEMS['alien-grenade']).toMatchObject({ damage: 90, damageType: 'he' }); expect(ITEMS['high-explosive']).toMatchObject({ damage: 110 }); expect(ITEMS['proximity-grenade']).toMatchObject({ damage: 70 }); });
  it('7. Stun Rod: 65 stun, melee 30% TU, accuracy 100', () => { expect(ITEMS['stun-rod']).toMatchObject({ damage: 65, damageType: 'stun' }); expect(ITEMS['stun-rod'].melee).toMatchObject({ tu: 30, accuracy: 100 }); });
  it('8. Blaster Bomb 200 HE, guided launcher; Stun Bomb 90 stun', () => { expect(ITEMS['blaster-bomb']).toMatchObject({ damage: 200, damageType: 'he' }); expect(ITEMS['blaster-launcher'].guided).toBe(true); expect(ITEMS['stun-bomb']).toMatchObject({ damage: 90, damageType: 'stun' }); });
  it('9. Rockets: small 75, large 100, incendiary 90', () => { expect(ITEMS['small-rocket'].damage).toBe(75); expect(ITEMS['large-rocket'].damage).toBe(100); expect(ITEMS['incendiary-rocket']).toMatchObject({ damage: 90, damageType: 'incendiary' }); });
  it('10. Grenade priming costs 50% TU and throwing 25% TU', () => { const g = ITEMS['grenade']; expect(g.primeTu ?? 50).toBe(50); expect(g.throwTu ?? 25).toBe(25); });
  it('11. Laser research chain: weapons(50) → pistol → rifle → heavy → cannon', () => { expect(RESEARCH['laser-weapons'].cost).toBe(50); expect(RESEARCH['laser-pistol'].requires).toContain('laser-weapons'); expect(RESEARCH['laser-rifle'].requires).toContain('laser-pistol'); expect(RESEARCH['heavy-laser'].requires).toContain('laser-rifle'); expect(RESEARCH['laser-cannon'].requires).toContain('heavy-laser'); });
  it('12. Artefact-gated research needs the recovered item; psi-amp needs the psi lab; decoder needs navigation', () => { expect(RESEARCH['plasma-pistol'].requiresItem).toBe('plasma-pistol'); expect(RESEARCH['blaster-launcher'].requiresItem).toBe('blaster-launcher'); expect(RESEARCH['psi-amp'].requires).toContain('psionic-laboratory'); expect(RESEARCH['hyper-wave-decoder'].requires).toContain('ufo-navigation'); });
  it('13. Endgame chain: alien-origins → the-martian-solution → cydonia-or-bust, via live leaders/commanders', () => { expect(RESEARCH['the-martian-solution'].requires).toContain('alien-origins'); expect(RESEARCH['cydonia-or-bust'].requires).toContain('the-martian-solution'); expect(RESEARCH['sectoid-commander'].getOneFree ?? []).toContain('cydonia-or-bust'); expect(RESEARCH['sectoid-leader'].getOneFree ?? []).toContain('the-martian-solution'); });
  it('14. Facility capacities and build times: quarters 50/16d, stores 50/10d, lab 50/26d, workshop 50/32d, containment 10/18d, hangar 25d', () => { expect(FACILITIES['living-quarters']).toMatchObject({ personnel: 50, buildDays: 16 }); expect(FACILITIES['general-stores']).toMatchObject({ stores: 50, buildDays: 10 }); expect(FACILITIES['laboratory']).toMatchObject({ labs: 50, buildDays: 26 }); expect(FACILITIES['workshop']).toMatchObject({ workshops: 50, buildDays: 32 }); expect(FACILITIES['alien-containment']).toMatchObject({ aliens: 10, buildDays: 18 }); expect(FACILITIES['hangar']).toMatchObject({ hangars: 1, buildDays: 25, size: 2 }); });
  it('15. Radar: small 1500 km at 10% per 30 min, large 2250 km at 20%, hyperwave 100%', () => { expect(FACILITIES['small-radar']).toMatchObject({ radarRange: 1500, radarChance: 10 }); expect(FACILITIES['large-radar']).toMatchObject({ radarRange: 2250, radarChance: 20 }); expect(FACILITIES['hyper-wave-decoder']).toMatchObject({ radarChance: 100, hyperwave: true }); });
  it('16. Craft: Skyranger 760 kt / 14 soldiers; Interceptor 2100 kt / 2 hardpoints; Avenger 5400 kt / 26 soldiers', () => { expect(CRAFT['skyranger']).toMatchObject({ speedMax: 760, soldiers: 14, weapons: 0 }); expect(CRAFT['interceptor']).toMatchObject({ speedMax: 2100, weapons: 2 }); expect(CRAFT['avenger']).toMatchObject({ speedMax: 5400, soldiers: 26 }); expect(CRAFT['firestorm'].speedMax).toBeGreaterThanOrEqual(4200); });
  it('17. Craft weapons: Stingray 70 dmg / 30 km / 6 shots; Avalanche 100 / 60 km / 3; Plasma Beam 140 / 52 km', () => { expect(CRAFT_WEAPONS['stingray']).toMatchObject({ damage: 70, range: 30, ammoMax: 6 }); expect(CRAFT_WEAPONS['avalanche']).toMatchObject({ damage: 100, range: 60, ammoMax: 3 }); expect(CRAFT_WEAPONS['plasma-beam']).toMatchObject({ damage: 140, range: 52 }); });
  it('18. UFOs: small scout 50 hull and unarmed; battleship 3200 hull, 148 power; terror ship 1200 hull', () => { expect(UFOS['small-scout']).toMatchObject({ damageMax: 50, weaponPower: 0 }); expect(UFOS['battleship']).toMatchObject({ damageMax: 3200, weaponPower: 148 }); expect(UFOS['terror-ship'].damageMax).toBe(1200); });
  it('19. Aliens: Sectoid soldier TU 54 / health 30; Muton soldier health 125; Chryssalid TU 110; Sectopod front armour 145', () => { expect(ALIENS['sectoid'].ranks.soldier?.stats).toMatchObject({ tu: 54, health: 30 }); expect(ALIENS['muton'].ranks.soldier?.stats.health).toBe(125); expect(ALIENS['chryssalid'].ranks.terrorist?.stats.tu).toBe(110); expect(ALIENS['sectopod'].ranks.terrorist?.armour.front).toBe(145); });
  it('20. Economy and clock: 8 soldiers / 10 scientists / 10 engineers at start; salaries 20k / 30k / 25k; compression 5s…1d', () => { expect(STARTING_STAFF).toMatchObject({ soldiers: 8, scientists: 10, engineers: 10 }); expect((FUNDING as any).salarySoldier ?? (FUNDING as any).salaries?.soldier).toBe(20000); expect((FUNDING as any).salaryScientist ?? (FUNDING as any).salaries?.scientist).toBe(30000); expect((FUNDING as any).salaryEngineer ?? (FUNDING as any).salaries?.engineer).toBe(25000); expect([...COMPRESSION_SECONDS]).toEqual([5, 60, 300, 1800, 3600, 86400]); });
});
