// Rasterises every SVG (hand-authored under assets/svg and generated by assets/gen/*.mjs) into packed
// spritesheets: public/atlas/<page>.png + .json (Pixi format, meta.scale = 2 → frames are device pixels).
// Also renders PWA icons. Nothing is rasterised at runtime.
import { readdir, readFile, writeFile, mkdir, stat } from 'node:fs/promises';
import { join, relative, sep } from 'node:path';
import { pathToFileURL } from 'node:url';
import { chromium } from 'playwright-core';

const ROOT = new URL('../../', import.meta.url).pathname;
const OUT = join(ROOT, 'public', 'atlas');
const PAGE = 4096, PAD = 2, UNIT_PX = 4; // viewBox unit → device px (2 CSS px × DPR 2)
const EXEC = '/opt/pw-browsers/chromium';

async function walk(dir) { const out = []; let ents = []; try { ents = await readdir(dir, { withFileTypes: true }); } catch { return out; } for (const e of ents) { const p = join(dir, e.name); if (e.isDirectory()) out.push(...(await walk(p))); else if (e.name.endsWith('.svg')) out.push(p); } return out; }

async function collect() {
  const sprites = [];
  for (const f of await walk(join(ROOT, 'assets', 'svg'))) {
    const name = relative(join(ROOT, 'assets', 'svg'), f).split(sep).join('/').replace(/\.svg$/, '');
    sprites.push({ name, svg: await readFile(f, 'utf8') });
  }
  let gens = []; try { gens = (await readdir(join(ROOT, 'assets', 'gen'))).filter((f) => f.endsWith('.mjs')).sort(); } catch {}
  for (const g of gens) {
    const mod = await import(pathToFileURL(join(ROOT, 'assets', 'gen', g)).href);
    const list = await mod.default();
    for (const s of list) sprites.push({ name: s.name, svg: s.svg, scale: s.scale });
  }
  const seen = new Set();
  for (const s of sprites) { if (seen.has(s.name)) throw new Error(`duplicate sprite name ${s.name}`); seen.add(s.name); }
  return sprites;
}

function viewBox(svg) { const m = svg.match(/viewBox="\s*([\d.-]+)[\s,]+([\d.-]+)[\s,]+([\d.-]+)[\s,]+([\d.-]+)\s*"/); if (!m) throw new Error('svg without viewBox'); return { w: +m[3], h: +m[4] }; }

async function main() {
  const sprites = await collect();
  console.log(`atlas: ${sprites.length} sprites`);
  await mkdir(OUT, { recursive: true });
  await mkdir(join(ROOT, 'public', 'icons'), { recursive: true });
  const browser = await chromium.launch({ executablePath: EXEC, args: ['--no-sandbox', '--disable-gpu'] });
  const page = await browser.newPage();
  await page.setContent('<html><body style="margin:0;background:transparent"></body></html>');
  // Rasterise + trim in the browser; returns per-sprite trimmed bitmaps as ImageData kept page-side.
  const metas = await page.evaluate(async ({ sprites, UNIT_PX }) => {
    window.__bitmaps = [];
    const metas = [];
    for (const s of sprites) {
      const m = s.svg.match(/viewBox="\s*([\d.-]+)[\s,]+([\d.-]+)[\s,]+([\d.-]+)[\s,]+([\d.-]+)\s*"/);
      const vw = +m[3], vh = +m[4]; const scale = (s.scale ?? 1) * UNIT_PX;
      const W = Math.round(vw * scale), H = Math.round(vh * scale);
      const svg = s.svg.replace(/<svg([^>]*)>/, (all, attrs) => `<svg${attrs.replace(/\s(width|height)="[^"]*"/g, '')} width="${W}" height="${H}">`);
      const url = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svg);
      const img = new Image(); img.decoding = 'sync';
      await new Promise((res, rej) => { img.onload = res; img.onerror = () => rej(new Error('bad svg ' + s.name)); img.src = url; });
      const c = document.createElement('canvas'); c.width = W; c.height = H; const ctx = c.getContext('2d', { willReadFrequently: true });
      ctx.imageSmoothingEnabled = true; ctx.drawImage(img, 0, 0, W, H);
      const d = ctx.getImageData(0, 0, W, H).data;
      let x0 = W, y0 = H, x1 = -1, y1 = -1;
      for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) { if (d[(y * W + x) * 4 + 3] > 0) { if (x < x0) x0 = x; if (x > x1) x1 = x; if (y < y0) y0 = y; if (y > y1) y1 = y; } }
      if (x1 < 0) { x0 = 0; y0 = 0; x1 = 0; y1 = 0; }
      const tw = x1 - x0 + 1, th = y1 - y0 + 1;
      const t = document.createElement('canvas'); t.width = tw; t.height = th; t.getContext('2d').drawImage(c, x0, y0, tw, th, 0, 0, tw, th);
      window.__bitmaps.push(t);
      metas.push({ name: s.name, W, H, x0, y0, tw, th });
    }
    return metas;
  }, { sprites, UNIT_PX });
  // Shelf packing by height into pages.
  const order = metas.map((m, i) => ({ ...m, i })).sort((a, b) => b.th - a.th || b.tw - a.tw);
  const pages = []; let cur = null;
  const newPage = () => { cur = { x: 0, y: 0, shelfH: 0, items: [] }; pages.push(cur); };
  newPage();
  for (const m of order) {
    const w = m.tw + PAD, h = m.th + PAD;
    if (w > PAGE || h > PAGE) throw new Error(`sprite too large ${m.name}`);
    if (cur.x + w > PAGE) { cur.x = 0; cur.y += cur.shelfH; cur.shelfH = 0; }
    if (cur.y + h > PAGE) { newPage(); }
    cur.items.push({ ...m, px: cur.x, py: cur.y }); cur.x += w; cur.shelfH = Math.max(cur.shelfH, h);
  }
  const pageNames = [];
  for (let p = 0; p < pages.length; p++) {
    const pg = pages[p]; if (!pg.items.length) continue; const usedH = Math.min(PAGE, pg.y + pg.shelfH);
    const name = `page${p}`; pageNames.push(name);
    const dataUrl = await page.evaluate(({ items, W, H }) => {
      const c = document.createElement('canvas'); c.width = W; c.height = H; const ctx = c.getContext('2d');
      for (const it of items) ctx.drawImage(window.__bitmaps[it.i], it.px, it.py);
      return c.toDataURL('image/png');
    }, { items: pg.items, W: PAGE, H: usedH });
    await writeFile(join(OUT, `${name}.png`), Buffer.from(dataUrl.split(',')[1], 'base64'));
    const frames = {};
    for (const it of pg.items) frames[it.name] = { frame: { x: it.px, y: it.py, w: it.tw, h: it.th }, rotated: false, trimmed: true, spriteSourceSize: { x: it.x0, y: it.y0, w: it.tw, h: it.th }, sourceSize: { w: it.W, h: it.H } };
    await writeFile(join(OUT, `${name}.json`), JSON.stringify({ frames, meta: { image: `${name}.png`, format: 'RGBA8888', size: { w: PAGE, h: usedH }, scale: '2' } }));
    console.log(`atlas: ${name} ${pg.items.length} frames, ${PAGE}x${usedH}`);
  }
  await writeFile(join(OUT, 'index.json'), JSON.stringify({ pages: pageNames, count: sprites.length, builtAt: new Date().toISOString() }));
  // PWA icons from assets/svg/app-icon.svg if present.
  try {
    const iconSvg = await readFile(join(ROOT, 'assets', 'app-icon.svg'), 'utf8');
    for (const [file, size] of [['icon-192.png', 192], ['icon-512.png', 512], ['apple-touch-icon.png', 180]]) {
      const url = await page.evaluate(async ({ svg, size }) => {
        const img = new Image(); await new Promise((res, rej) => { img.onload = res; img.onerror = rej; img.src = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svg); });
        const c = document.createElement('canvas'); c.width = size; c.height = size; c.getContext('2d').drawImage(img, 0, 0, size, size); return c.toDataURL('image/png');
      }, { svg: iconSvg, size });
      await writeFile(join(ROOT, 'public', 'icons', file), Buffer.from(url.split(',')[1], 'base64'));
    }
  } catch (e) { console.warn('icons skipped:', e.message); }
  await browser.close();
}
main().catch((e) => { console.error(e); process.exit(1); });
