// Data helpers used by the base simulation.
import { FACILITIES, facilityDef as fDef } from '../data/facilities';
import { ITEMS } from '../data/items';
import { CRAFT, CRAFT_WEAPONS } from '../data/craft';
import { REGIONS } from '../data/countries';
import { FUNDING } from '../data/score';
import type { FacilityDef, ItemDef, CraftTypeDef, CraftWeaponDef, RegionDef } from '../data/types';
export type PersonnelKind = 'soldier' | 'scientist' | 'engineer';
export const facilityDef = (id: string): FacilityDef | undefined => fDef(id);
export const allFacilities = (): FacilityDef[] => Object.values(FACILITIES);
export const itemDef = (id: string): ItemDef | undefined => ITEMS[id];
export const allItems = (): ItemDef[] => Object.values(ITEMS);
export const craftDef = (id: string): CraftTypeDef | undefined => CRAFT[id];
export const allCraftTypes = (): CraftTypeDef[] => Object.values(CRAFT);
export const craftWeaponDef = (id: string): CraftWeaponDef | undefined => CRAFT_WEAPONS[id];
export const craftWeaponForItem = (itemId: string): CraftWeaponDef | undefined => Object.values(CRAFT_WEAPONS).find((w) => w.storeItem === itemId);
export const allRegions = (): RegionDef[] => Object.values(REGIONS);
export const liftDefId = () => 'access-lift';
export const hireCost = (kind: PersonnelKind) => FUNDING.hire[kind];
export const salary = (kind: PersonnelKind) => FUNDING.salaries[kind];
export const PERSONNEL_HOURS = FUNDING.personnelDeliveryHours;
export const itemHours = (d: ItemDef) => d.transferHours ?? 24;
export const craftHours = (d: CraftTypeDef) => d.transferHours ?? 72;
